#!/usr/bin/env python3
"""
OpenClaude — Setup Wizard
Generates workspace configuration, CLAUDE.md, .env, and folder structure.
Usage: python setup.py  (or: make setup)
"""

import os
import shutil
import sys
from pathlib import Path

WORKSPACE = Path(__file__).parent

# ANSI colors
GREEN = "\033[92m"
CYAN = "\033[96m"
YELLOW = "\033[93m"
DIM = "\033[2m"
BOLD = "\033[1m"
RESET = "\033[0m"


def banner():
    print(f"""
{GREEN}  ╔══════════════════════════════════╗
  ║   {BOLD}OpenClaude — Setup Wizard{RESET}{GREEN}     ║
  ╚══════════════════════════════════╝{RESET}
""")


def ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    val = input(f"  {CYAN}>{RESET} {prompt}{suffix}: ").strip()
    return val or default


def ask_bool(prompt: str, default: bool = True) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    val = input(f"  {CYAN}>{RESET} {prompt} {suffix}: ").strip().lower()
    if not val:
        return default
    return val in ("y", "yes", "1", "true")


def ask_multi(prompt: str, options: list[dict], defaults: list[str] = None) -> list[str]:
    """Multi-select with checkboxes."""
    if defaults is None:
        defaults = []
    selected = set(defaults)

    print(f"\n  {prompt}")
    for opt in options:
        key = opt["key"]
        label = opt["label"]
        desc = opt.get("desc", "")
        checked = "x" if key in selected else " "
        desc_str = f" — {DIM}{desc}{RESET}" if desc else ""
        print(f"  [{checked}] {label}{desc_str}")

    print(f"\n  {DIM}Enter keys to toggle (comma-separated), or press Enter to accept:{RESET}")
    val = input(f"  {CYAN}>{RESET} ").strip()

    if val:
        for key in val.replace(" ", "").split(","):
            key = key.strip().lower()
            if key in {o["key"] for o in options}:
                if key in selected:
                    selected.discard(key)
                else:
                    selected.add(key)

    return list(selected)


AGENTS = [
    {"key": "ops", "label": "ops", "desc": "Daily operations (briefing, email, tasks)"},
    {"key": "finance", "label": "finance", "desc": "Financial (P&L, cash flow, invoices)"},
    {"key": "projects", "label": "projects", "desc": "Project management (sprints, milestones)"},
    {"key": "community", "label": "community", "desc": "Community (Discord, WhatsApp pulse)"},
    {"key": "social", "label": "social", "desc": "Social media (content, analytics)"},
    {"key": "strategy", "label": "strategy", "desc": "Strategy (OKRs, roadmap)"},
    {"key": "sales", "label": "sales", "desc": "Commercial (pipeline, proposals)"},
    {"key": "courses", "label": "courses", "desc": "Education (course creation)"},
    {"key": "personal", "label": "personal", "desc": "Personal (health, habits)"},
]

INTEGRATIONS = [
    {"key": "google_calendar", "label": "Google Calendar + Gmail"},
    {"key": "todoist", "label": "Todoist"},
    {"key": "discord", "label": "Discord"},
    {"key": "telegram", "label": "Telegram"},
    {"key": "whatsapp", "label": "WhatsApp"},
    {"key": "stripe", "label": "Stripe"},
    {"key": "omie", "label": "Omie ERP"},
    {"key": "github", "label": "GitHub"},
    {"key": "linear", "label": "Linear"},
    {"key": "youtube", "label": "YouTube"},
    {"key": "instagram", "label": "Instagram"},
    {"key": "linkedin", "label": "LinkedIn"},
    {"key": "fathom", "label": "Fathom (meetings)"},
]

DEFAULT_FOLDERS = {
    "daily_logs": "daily-logs",
    "projects": "projects",
    "community": "community",
    "social": "social",
    "finance": "finance",
    "meetings": "meetings",
    "courses": "courses",
    "strategy": "strategy",
}


def generate_workspace_yaml(config: dict) -> str:
    lines = [
        "# OpenClaude Workspace Configuration",
        f"# Generated by setup.py on {config['date']}",
        "",
        "workspace:",
        f'  name: "{config["workspace_name"]}"',
        f'  owner: "{config["owner_name"]}"',
        f'  company: "{config["company_name"]}"',
        f'  timezone: "{config["timezone"]}"',
        f'  language: "{config["language"]}"',
        "",
        "# Folder structure",
        "folders:",
    ]
    for key, val in config["folders"].items():
        lines.append(f'  {key}: "{val}"')

    lines += ["", "# Active agents", "agents:"]
    for agent in AGENTS:
        enabled = "true" if agent["key"] in config["agents"] else "false"
        lines.append(f"  {agent['key']}: {enabled}")

    lines += ["", "# Integrations (configure API keys in .env)", "integrations:"]
    for integ in INTEGRATIONS:
        enabled = "true" if integ["key"] in config["integrations"] else "false"
        lines.append(f"  {integ['key']}: {enabled}")

    lines += [
        "",
        "# Dashboard",
        "dashboard:",
        f"  port: {config['dashboard_port']}",
        '  secret_key: ""  # auto-generated if empty',
        "",
    ]
    return "\n".join(lines)


def generate_claude_md(config: dict) -> str:
    template = (WORKSPACE / "CLAUDE.template.md").read_text()

    replacements = {
        "{{workspace_name}}": config["workspace_name"],
        "{{owner_name}}": config["owner_name"],
        "{{owner_role}}": config.get("owner_role", "CEO"),
        "{{company_name}}": config["company_name"],
        "{{timezone}}": config["timezone"],
        "{{language}}": config["language"],
        "{{skill_count}}": str(len(list((WORKSPACE / ".claude" / "skills").iterdir())) if (WORKSPACE / ".claude" / "skills").is_dir() else 0),
    }

    for key, folder in config["folders"].items():
        replacements[f"{{{{{key}}}}}"] = folder
        replacements[f"{{{{folder_{key}}}}}"] = folder

    result = template
    for placeholder, value in replacements.items():
        result = result.replace(placeholder, value)

    # Remove mustache blocks ({{#agents}} ... {{/agents}}) — simplified
    # In a real implementation, use a proper template engine
    # For now, build the agents table manually
    agent_table = ""
    for agent in AGENTS:
        if agent["key"] in config["agents"]:
            agent_table += f"| **{agent['label'].title()}** | `/{agent['key']}` | {agent['desc']} |\n"

    # Replace the agents block
    import re
    result = re.sub(
        r'\{\{#agents\}\}.*?\{\{/agents\}\}',
        agent_table.strip(),
        result,
        flags=re.DOTALL,
    )

    # Remove integration blocks (simplified)
    result = re.sub(r'\{\{#integrations\}\}.*?\{\{/integrations\}\}', '', result, flags=re.DOTALL)

    return result


def copy_env_example(config: dict):
    src = WORKSPACE / ".env.example"
    dst = WORKSPACE / ".env"
    if dst.exists():
        print(f"  {YELLOW}!{RESET} .env already exists, skipping")
        return
    if src.exists():
        shutil.copy2(src, dst)
        print(f"  {GREEN}✓{RESET} Created .env from .env.example")
    else:
        print(f"  {YELLOW}!{RESET} .env.example not found, creating empty .env")
        dst.write_text("# OpenClaude Environment Variables\n# Fill in your API keys below\n\n")


def copy_routines_config(config: dict):
    src = WORKSPACE / "config" / "routines.yaml.example"
    dst = WORKSPACE / "config" / "routines.yaml"
    if dst.exists():
        print(f"  {YELLOW}!{RESET} config/routines.yaml already exists, skipping")
        return
    if src.exists():
        shutil.copy2(src, dst)
        print(f"  {GREEN}✓{RESET} Created config/routines.yaml")


def create_folders(config: dict):
    count = 0
    for key, name in config["folders"].items():
        folder = WORKSPACE / name
        folder.mkdir(exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.touch()
        count += 1

    # Data dirs
    for d in ["data", "memory"]:
        (WORKSPACE / d).mkdir(exist_ok=True)

    print(f"  {GREEN}✓{RESET} Created workspace folders ({count})")


def main():
    banner()

    # Step 1 — Who are you?
    print(f"  {BOLD}Step 1/5 — Who are you?{RESET}")
    owner_name = ask("Your name", "")
    company_name = ask("Company name", "")
    timezone = ask("Timezone", "America/Sao_Paulo")
    language = ask("Language", "en")
    print()

    # Step 2 — Agents
    print(f"  {BOLD}Step 2/5 — Which agents do you want?{RESET}")
    default_agents = ["ops", "finance", "projects", "community"]
    agents = ask_multi("Select agents:", AGENTS, default_agents)
    print()

    # Step 3 — Integrations
    print(f"  {BOLD}Step 3/5 — Integrations{RESET}")
    print(f"  {DIM}Configure API keys in .env after setup.{RESET}")
    integrations = ask_multi("Select integrations:", INTEGRATIONS, [])
    print()

    # Step 4 — Dashboard
    print(f"  {BOLD}Step 4/5 — Dashboard{RESET}")
    enable_dashboard = ask_bool("Enable web dashboard?", True)
    dashboard_port = int(ask("Dashboard port", "8080")) if enable_dashboard else 8080
    print()

    # Build config
    from datetime import date
    config = {
        "date": date.today().isoformat(),
        "workspace_name": f"{company_name or owner_name} Workspace",
        "owner_name": owner_name,
        "company_name": company_name,
        "timezone": timezone,
        "language": language,
        "agents": agents,
        "integrations": integrations,
        "folders": DEFAULT_FOLDERS.copy(),
        "dashboard_port": dashboard_port,
    }

    # Step 5 — Generate
    print(f"  {BOLD}Step 5/5 — Creating workspace...{RESET}")

    # workspace.yaml
    config_dir = WORKSPACE / "config"
    config_dir.mkdir(exist_ok=True)
    (config_dir / "workspace.yaml").write_text(generate_workspace_yaml(config))
    print(f"  {GREEN}✓{RESET} Generated config/workspace.yaml")

    # .env
    copy_env_example(config)

    # routines.yaml
    copy_routines_config(config)

    # CLAUDE.md
    claude_md = generate_claude_md(config)
    (WORKSPACE / "CLAUDE.md").write_text(claude_md)
    print(f"  {GREEN}✓{RESET} Generated CLAUDE.md")

    # Folders
    create_folders(config)

    # Dashboard build
    if enable_dashboard:
        frontend_dir = WORKSPACE / "dashboard" / "frontend"
        if (frontend_dir / "package.json").exists():
            print(f"  {DIM}Building dashboard frontend...{RESET}")
            os.system(f"cd {frontend_dir} && npm install --silent && npm run build --silent 2>/dev/null")
            print(f"  {GREEN}✓{RESET} Built dashboard frontend")

    print(f"""
  {GREEN}Done!{RESET} Next steps:
  1. Edit {BOLD}.env{RESET} with your API keys
  2. Run: {BOLD}make dashboard{RESET}    — start web UI
  3. Run: {BOLD}make scheduler{RESET}    — start automated routines
  4. Run: {BOLD}make help{RESET}         — see all commands
""")


if __name__ == "__main__":
    main()
